apiVersion: v1
kind: Service
metadata:
    labels:
      app: wildfly-rollout 
    name: rollout-bluegreen-preview
spec:
  ports:
  - nodePort: 30200
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: wildfly-rollout
  type: NodePort
status:
  loadBalancer: {}
